# Generated by Django 3.2.6 on 2021-08-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='fees_in_world',
            field=models.PositiveIntegerField(default=0, help_text='бюджета е в долари', verbose_name='Приходи в световен мащаб'),
        ),
    ]
