# Generated by Django 3.2.6 on 2021-08-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_fees_in_world'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='Чернова'),
        ),
    ]
