# Generated by Django 3.2.6 on 2021-08-13 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieshot',
            name='image',
            field=models.ImageField(upload_to='movie_shots/', verbose_name='Изображение'),
        ),
    ]
